### ISSUE TITLE
번역 데이터 수정 및 적용

### ISSUE THREAD

**Issue by KimJi-An** [kakao-tech-campus-2nd-step3/Team18_FE#102]
## Description
번역 데이터 수정/추가를 진행합니다.

## Tasks
- [x] RecruitmentInfo의 공고글 제목 언어 수정
- [x] RecruitmentTable의 공고글 제목 언어 수정
- [x] Header 데이터 추가
- [x] 계약서 팝업 데이터 추가
