### ISSUE TITLE
i18n 번역 데이터 생성 및 적용

### ISSUE THREAD

**Issue by tteokbokki-master** [kakao-tech-campus-2nd-step3/Team18_FE#104]
## Description
담당 페이지들에 대한 번역 데이터를 만들고 적용할 예정입니다. 응원 바람

## Tasks
- [x] Footer 번역 데이터 생성
- [x] 구인글 상세화면 번역 데이터 생성
- [x] 지원 프로세스 번역 데이터 생성
- [x] 지원서 페이지 번역 데이터 생성
- [x] 사인 등록 페이지 번역 데이터 생성
