### ISSUE TITLE
회사 등록 버튼 추가

### ISSUE THREAD

**Issue by KimJi-An** [kakao-tech-campus-2nd-step3/Team18_FE#106]
## Description
고용주 마이페이지에 회사 등록 버튼을 추가합니다.

## Tasks
- [x] 회사 등록 버튼 추가
- [x] 버튼 클릭 시 회사 등록 페이지로 이동 
- [x] 번역 데이터에 회사 등록 추가
- [x] 반응형 디자인 수정
