### ISSUE TITLE
마감하기 API 경로 수정 및 고용주 사인 등록 완료 시 버튼 비활성화

### ISSUE THREAD

**Issue by KimJi-An** [kakao-tech-campus-2nd-step3/Team18_FE#136]
## Description
마감하기 API 경로를 올바르게 수정하고, 마감 완료 시 버튼을 비활성화합니다.

## Tasks
- [x] 마감하기 API 경로 `api/recruitments/hiringClose/{recruitmentId}`로 수정
- [x] 마감 완료 시 버튼 비활성화
- [x] 고용주 사인 등록 완료 시 사인 등록 버튼 비활성화
