### ISSUE TITLE
고용주 마이페이지 구현

### ISSUE THREAD

**Issue by KimJi-An** [kakao-tech-campus-2nd-step3/Team18_FE#32]
## Description
고용주 마이페이지를 구현합니다.

### 피그마 화면
<img src="https://github.com/user-attachments/assets/fe88305a-045e-4fb2-a50c-96b2520bc201" width="700px" />

## Tasks
- [x] 회사 정보 부분과 내 공고글 부분 분리
- [x] 회사 정보에서 홈페이지 링크, 전화번호, 이메일 주소는 제외
- [x] 마감하기 버튼 추가
