### ISSUE TITLE
9주차 기능 개선 및 리팩토링

### ISSUE THREAD

**Issue by KimJi-An** [kakao-tech-campus-2nd-step3/Team18_FE#71]
## Description
고용주 마이페이지, 지원자 목록 페이지, 계약하기 팝업에 대한 리팩토링을 진행합니다.
## Tasks
- 고용주 마이페이지 
  - [x] 사인 등록 버튼 추가
  - [x] 사인 등록 버튼 클릭 시 해당 페이지로 이동 
- 지원자 목록 페이지
  - [x] 리뷰 반영
- 계약하기 팝업
  - [x] 버튼들 분리
  - [x] 확인 버튼 클릭 시 계약서 페이지로 이동
