### ISSUE TITLE
구인 글 상세 화면 수정 및 API 연결

### ISSUE THREAD

**Issue by tteokbokki-master** [kakao-tech-campus-2nd-step3/Team18_FE#81]
## Description
구인글 상세 화면 수정과 api 연결을 진행하겠습니다.

## Tasks
- [x] recruitmentsDetail 스타일 변경
- [x] api 명세서에 맞게 타입 구조 변경
- [x] api 연동 (msw)
