### ISSUE TITLE
Header 컴포넌트 기능 추가 및 개선

### ISSUE THREAD

**Issue by KimJi-An** [kakao-tech-campus-2nd-step3/Team18_FE#85]
## Description
Header의 기능을 추가 및 개선합니다.

## Tasks
- [x] 로고 클릭 시 홈 화면으로 이동
- [x] 로그인 버튼 클릭 시 로그인 페이지로 이동
- [x] 채용공고 등록 클릭 시 구인글 업로드 페이지로 이동
- [x] 유저 프로필 이미지 클릭 시 해당 마이페이지로 이동
- [x] 로그인 상태(로그인 여부 및 고용주/근로자)에 따른 구분
