### ISSUE TITLE
9주차 코드리뷰 리팩토링

### ISSUE THREAD

**Issue by KimJi-An** [kakao-tech-campus-2nd-step3/Team18_FE#95]
## Description
9주차 코드 리뷰에 대한 리팩토링을 진행합니다.

## Tasks
- [x] 로컬 스토리지 접근 추상화
- [x] 이벤트 핸들러와 함수 구분
- [x] 폴더 간 의존성 고려
- [x] MyCompany 페이지 분리
- [x] Applicants 페이지 분리
